### ISSUE TITLE
Model multiple variants of the virus

### ISSUE THREAD

**Issue by tedkyi** [daveselinger/covid_rapid_test_simulation2#1]
Track which variant each actor is infected with, since spread may be different (based on properties of the variant)

**Comment by tedkyi** [comment]
I have added variant to the `Infection` class.  When someone gets infected, they will have the same variant as the person who exposed them.
TODO:  None of the behavior currently depends on the variant type.  Should we close this issue and create separate issues for the behaviors that we want to differ by variant type?

**Comment by devvidhani** [comment]
@tedkyi  -- shouldn't the order of startingVariantMix be in decreasing order for random pickup to work efficiently?

**Comment by tedkyi** [comment]
As long as the probabilities add up to one, the order doesn't matter.

**Comment by devvidhani** [comment]
You are right. for these small # of categories, doesn't matter.

**Comment by tedkyi** [comment]
With the merge of PR #13, I think this issue is complete.  I am closing it.
Let's track the need for new parameters, or the desire to change code to parameterize effects per variant, in new issues.
