### ISSUE TITLE
Vaccine breakthrough and reinfections

### ISSUE THREAD

**Issue by rstager** [daveselinger/covid_rapid_test_simulation2#5]
Model vaccine breakthroughs.  Model should consider vaccine type, time since vaccination, actor demographics (i.e. age)

The actor should track a history of prior infections

This is related to vaccine waning.

Reinfections occur when an actor is infected with the same or a different variant.

**Comment by rstager** [comment]
The existing code already has a vaccine efficacy rate. However, cross variant protection is not modeled.

**Comment by tedkyi** [comment]
Started update of vaccine efficacy by making it per variant.  Added this commit to PR #16.
Next step will be to have it wane over time.
